### ISSUE TITLE
Add function that return the number of objects for a sequence

### ISSUE THREAD

**Issue by scaelles** [albertomontesg/davis-interactive#13]

**Comment by albertomontesg** [comment]
This information can be inferred from the annotation (the same way it is done with the PNG masks) or also checking the `Davis` class which gives additional information for every sequence (resolution, number of objects, number of frames).

Should we give this information at the scribbles annotation or in some other way which is the same for the sequence and make the annotations (masks, scribbles) independent?

**Comment by scaelles** [comment]
Then, probably the easiest is to have a function in utils that given the sequence name it return the number of objects.
Let's keep the scribbles data simple with only the scribbles and the sequence name.

**Comment by scaelles** [comment]
Use the DAVIS class in the following way:
from davisinteractive.dataset import Davis

davis = Davis(davis_root='/path/to//DAVIS')

n_objects = davis.dataset['sequences'][sequence]['num_objects']
