### ISSUE TITLE
import davisinteractive.session does not work

### ISSUE THREAD

**Issue by kmaninis** [albertomontesg/davis-interactive#24]
The modules of the package are not there when used pip install davisinteractive.
Tested with conda version : 4.5.1

![image](https://user-images.githubusercontent.com/15798030/39140059-d34e1f1a-4723-11e8-8d8f-b777c653a5ee.png)

**Comment by albertomontesg** [comment]
Should be fixed with commit f34d8fd4617fc786950bf43b02f6dd7eafa7a284
