### ISSUE TITLE
Get scribble of false positive for a particular object

### ISSUE THREAD

**Issue by zyy-cn** [albertomontesg/davis-interactive#54]
Hi:

The scribbles drawn by the robot is based on error_mask generated using a particular obj_id by
 `        for obj_id in obj_ids:
            error_mask = (gt == obj_id) & (pred != obj_id)`
however, it will mix all the false positive refers to different instances when obj_id is '0', and I cannot easily separate them when I trying to get the scribble of false positive for the particular instance in the scribbles_data like 'FP scribble for instance 1 and FP scribble for instance 2'. Is any solution for this issue?

**Comment by scaelles** [comment]
Hello,

That's right, the robot gives scribbles for false positive without saying to which object that scribble belonged. That's an intended behavior as we see the human just saying that the false positive should belong to background. However, you could compute the overlap of the mask that you submitted with the scribbles that you received. Then, you can have for every pixel of the scribble which object it belongs to.

Let us know if you have any further question.

**Comment by zyy-cn** [comment]
@scaelles This is really a good way to do it. Thanks for your advice!
