### ISSUE TITLE
Can you provide this visualization result like this?

### ISSUE THREAD

**Issue by longmalongma** [albertomontesg/davis-interactive#62]
Can you provide this visualization result like this?

![e7b7d6f4cf0786ecc9cf639af5dd179](https://user-images.githubusercontent.com/40291722/139029954-5d18519f-5184-4797-8d3c-75b93fbb5f59.png)

**Comment by scaelles** [comment]
Hello,

I believe that figure corresponds to a paper not published by our team. Therefore, I would suggest to contact the authors of that paper directly to get those cool visualizations!

Best,
Sergi Caelles
